name: RestApi
description: A sample rest full web service
dependencies:
  browser: any
  http_server: any
  redstone: any
  start: any
  shelf: any
  redstone_mapper: any
  shelf_route: ">=0.9.0 <0.10.0"
  shelf_bind: ">=0.6.1+4 <0.7.0"
  shelf_exception_response: any